#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-grolifant
Version  : 0.10
Release  : 1
URL      : https://gitlab.com/ysb33rOrg/grolifant/-/archive/RELEASE_0_10/grolifant-RELEASE_0_10.tar.gz
Source0  : https://gitlab.com/ysb33rOrg/grolifant/-/archive/RELEASE_0_10/grolifant-RELEASE_0_10.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/org/ysb33r/gradle/grolifant/0.10/grolifant-0.10.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/ysb33r/gradle/grolifant/0.10/grolifant-0.10.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-grolifant-data = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
= Grolifant Gradle Plugin Support Library
The purpose of this library is provide certain building blocks which are key to writing various
kinds of Gradle plugins, but which are not easily obtainable from Gradle core itself.

%package data
Summary: data components for the mvn-grolifant package.
Group: Data

%description data
data components for the mvn-grolifant package.


%prep
%setup -q -n grolifant-RELEASE_0_10

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ysb33r/gradle/grolifant/0.10
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/ysb33r/gradle/grolifant/0.10/grolifant-0.10.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ysb33r/gradle/grolifant/0.10
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/ysb33r/gradle/grolifant/0.10/grolifant-0.10.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/ysb33r/gradle/grolifant/0.10/grolifant-0.10.jar
/usr/share/java/.m2/repository/org/ysb33r/gradle/grolifant/0.10/grolifant-0.10.pom
